---
kind: pipeline
name: default
steps:
  - name: lint
    image: python:3.11-slim
    commands:
      - pip install ".[dev]"
      - ruff check .
      - mypy .
      - djlint --lint src/micronote/templates
  - name: test
    image: python:3.11-slim
    commands:
      - pip install ".[dev]"
      - cp tests/fixtures/me.yml config/me.yml
      - python -m pytest tests/integration_test.py -v
  - name: docker
    image: docker:dind
    commands:
      - docker build . -t micronote:latest
