services:
  web:
    image: 'micronote:latest'
    ports:
     - "${WEB_PORT}:5005"
    volumes:
     - "${CONFIG_DIR}:/app/config"
     - "${DATA_DIR}:/app/data"
     - "./static:/app/static"
    environment:
     - MICRONOTE_DEBUG=1
  worker:
    image: 'micronote:latest'
    command: 'python worker.py'
    volumes:
     - "${CONFIG_DIR}:/app/config"
     - "${DATA_DIR}:/app/data"
    environment:
     - MICRONOTE_DEBUG=1
networks:
  default:
    name: microblogpubfede 
