services:
  web:
    image: 'micronote:latest'
    ports:
     - "${WEB_PORT}:5005"
    volumes:
     - "${CONFIG_DIR}:/app/config"
     - "${DATA_DIR}:/app/data"
     - "./src/micronote/static:/app/src/micronote/static"
    environment:
     - MICRONOTE_DEBUG=1
  worker:
    image: 'micronote:latest'
    command: 'python -m micronote.worker'
    volumes:
     - "${CONFIG_DIR}:/app/config"
     - "${DATA_DIR}:/app/data"
    environment:
     - MICRONOTE_DEBUG=1
